[package]
name = "features"
version = "0.1.0"
authors = ["Edgar Riba <edgar.riba@gmail.com>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
argh = { workspace = true }
kornia = { workspace = true }
rerun = { workspace = true }
